Repository avasachinbaijal/AvaTax-REST-V3-Ruby-SDK, pull requests merged in 2022-02, with the labels that each got.

#1 Update for 2.3.0
  .openapi-generator/FILES
  .travis.yml
  Avalara.SDK.gemspec
  README.md
  docs/AgeVerificationApi.md
  docs/AgeVerifyFailureCode.md
  docs/AgeVerifyRequest.md
  docs/AgeVerifyRequestAddress.md
  docs/AgeVerifyResult.md
  docs/ErrorDetails.md
  docs/ErrorDetailsError.md
  docs/ErrorDetailsErrorDetails.md
  docs/ShippingVerificationApi.md
  docs/ShippingVerifyResult.md
  docs/ShippingVerifyResultLines.md
  lib/Avalara.SDK.rb
  lib/Avalara.SDK/api/age_verification_api.rb
  lib/Avalara.SDK/api/shipping_verification_api.rb
  lib/Avalara.SDK/api_client.rb
  lib/Avalara.SDK/api_error.rb
  lib/Avalara.SDK/configuration.rb
  lib/Avalara.SDK/models/age_verify_failure_code.rb
  lib/Avalara.SDK/models/age_verify_request.rb
  lib/Avalara.SDK/models/age_verify_request_address.rb
  lib/Avalara.SDK/models/age_verify_result.rb
  lib/Avalara.SDK/models/error_details.rb
  lib/Avalara.SDK/models/error_details_error.rb
  lib/Avalara.SDK/models/error_details_error_details.rb
  lib/Avalara.SDK/models/shipping_verify_result.rb
  lib/Avalara.SDK/models/shipping_verify_result_lines.rb
  lib/Avalara.SDK/version.rb
  spec/api_client_spec.rb
  spec/configuration_spec.rb
  spec/spec_helper.rb
Labels: 2.3.0

#15 Update for 2.4.5.5
  .openapi-generator/FILES
  .travis.yml
  README.md
  avalara_sdk.gemspec
  docs/AgeVerificationApi.md
  docs/AgeVerifyFailureCode.md
  docs/AgeVerifyRequest.md
  docs/AgeVerifyRequestAddress.md
  docs/AgeVerifyResult.md
  docs/ErrorDetails.md
  docs/ErrorDetailsError.md
  docs/ErrorDetailsErrorDetails.md
  docs/ShippingVerificationApi.md
  docs/ShippingVerifyResult.md
  docs/ShippingVerifyResultLines.md
  lib/avalara_sdk.rb
  lib/avalara_sdk/api/age_verification_api.rb
  lib/avalara_sdk/api/shipping_verification_api.rb
  lib/avalara_sdk/models/age_verify_failure_code.rb
  lib/avalara_sdk/models/age_verify_request.rb
  lib/avalara_sdk/models/age_verify_request_address.rb
  lib/avalara_sdk/models/age_verify_result.rb
  lib/avalara_sdk/models/error_details.rb
  lib/avalara_sdk/models/error_details_error.rb
  lib/avalara_sdk/models/error_details_error_details.rb
  lib/avalara_sdk/models/shipping_verify_result.rb
  lib/avalara_sdk/models/shipping_verify_result_lines.rb
  spec/api_client_spec.rb
  spec/configuration_spec.rb
  spec/spec_helper.rb
Labels: 2.4.5.5

#16 Update for 2.4.5.6
  .openapi-generator/FILES
  .travis.yml
  README.md
  avalara_sdk.gemspec
  lib/avalara_sdk.rb
  lib/avalara_sdk/api/age_verification_api.rb
  lib/avalara_sdk/api/shipping_verification_api.rb
  lib/avalara_sdk/models/age_verify_failure_code.rb
  lib/avalara_sdk/models/age_verify_request.rb
  lib/avalara_sdk/models/age_verify_request_address.rb
  lib/avalara_sdk/models/age_verify_result.rb
  lib/avalara_sdk/models/error_details.rb
  lib/avalara_sdk/models/error_details_error.rb
  lib/avalara_sdk/models/error_details_error_details.rb
  lib/avalara_sdk/models/shipping_verify_result.rb
  lib/avalara_sdk/models/shipping_verify_result_lines.rb
  lib/avalara_sdk/version.rb
  spec/api_client_spec.rb
  spec/configuration_spec.rb
  spec/spec_helper.rb
Labels: 2.4.5.6

#17 Update for 2.4.6
  .travis.yml
  README.md
  avalara_sdk.gemspec
  lib/avalara_sdk.rb
  lib/avalara_sdk/api/age_verification_api.rb
  lib/avalara_sdk/api/shipping_verification_api.rb
  lib/avalara_sdk/models/age_verify_failure_code.rb
  lib/avalara_sdk/models/age_verify_request.rb
  lib/avalara_sdk/models/age_verify_request_address.rb
  lib/avalara_sdk/models/age_verify_result.rb
  lib/avalara_sdk/models/error_details.rb
  lib/avalara_sdk/models/error_details_error.rb
  lib/avalara_sdk/models/error_details_error_details.rb
  lib/avalara_sdk/models/shipping_verify_result.rb
  lib/avalara_sdk/models/shipping_verify_result_lines.rb
  lib/avalara_sdk/version.rb
  spec/api_client_spec.rb
  spec/configuration_spec.rb
  spec/spec_helper.rb
Labels: 2.4.6

#18 Update for 2.4.7
  .openapi-generator/FILES
  .travis.yml
  README.md
  avalara_sdk.gemspec
  lib/avalara_sdk.rb
  lib/avalara_sdk/api/age_verification_api.rb
  lib/avalara_sdk/api/shipping_verification_api.rb
  lib/avalara_sdk/models/age_verify_failure_code.rb
  lib/avalara_sdk/models/age_verify_request.rb
  lib/avalara_sdk/models/age_verify_request_address.rb
  lib/avalara_sdk/models/age_verify_result.rb
  lib/avalara_sdk/models/error_details.rb
  lib/avalara_sdk/models/error_details_error.rb
  lib/avalara_sdk/models/error_details_error_details.rb
  lib/avalara_sdk/models/shipping_verify_result.rb
  lib/avalara_sdk/models/shipping_verify_result_lines.rb
  lib/avalara_sdk/version.rb
Labels: 2.4.7

#41 Update for 2.4.26
  .travis.yml
  README.md
  avalara_sdk.gemspec
  docs/AgeVerificationApi.md
  docs/ShippingVerificationApi.md
  lib/avalara_sdk.rb
  lib/avalara_sdk/api/age_verification_api.rb
  lib/avalara_sdk/api/shipping_verification_api.rb
  lib/avalara_sdk/models/age_verify_failure_code.rb
  lib/avalara_sdk/models/age_verify_request.rb
  lib/avalara_sdk/models/age_verify_request_address.rb
  lib/avalara_sdk/models/age_verify_result.rb
  lib/avalara_sdk/models/error_details.rb
  lib/avalara_sdk/models/error_details_error.rb
  lib/avalara_sdk/models/error_details_error_details.rb
  lib/avalara_sdk/models/shipping_verify_result.rb
  lib/avalara_sdk/models/shipping_verify_result_lines.rb
  lib/avalara_sdk/version.rb
Labels: 2.4.26
